ingredient_type_mapping = {
    "Port": "Wine",
    "Tabasco Sauce": "Sauce",
    "Pineapple Juice": "Juice",
    "Sweet Vermouth": "Fortified Wine",
    "Orange spiral": "Fruit",
    "Egg": "Unknown",  # lub coś bardziej odpowiedniego
    "Maraschino Cherry": "Fruit",
    "Lemon vodka": "Vodka",
    "Powdered Sugar": "Unknown",
    "Lemon Juice": "Juice",
    "Whipped Cream": "Cream",
    "Bitters": "Bitters",
    "Celery Salt": "Unknown",
    "Heavy cream": "Cream",
    "Champagne": "Wine",
    "Raspberry syrup": "Syrup",
    "Dark Rum": "Rum",
    "Salt": "Mineral",
    "Dubonnet Rouge": "Fortified Wine",
    "Green Chartreuse": "Liqueur",
    "Ginger Ale": "Soft Drink",
    "Maraschino Liqueur": "Liqueur",
    "Orange Peel": "Fruit",
    "Cherry": "Fruit",
    "Scotch": "Whisky",
    "Orgeat Syrup": "Syrup",
    "Sherry": "Fortified Wine",
    "Carbonated Water": "Water",
    "Olive": "Fruit",
    "Cherry Brandy": "Brandy",
    "Brandy": "Brandy",
    "Grand Marnier": "Liqueur",
    "Red Wine": "Wine",
    "Sugar Syrup": "Syrup",
    "Sloe Gin": "Gin",
    "Soda water": "Soda",
    "Coffee Liqueur": "Liqueur",
    "Blackberry Brandy": "Brandy",
    "Cognac": "Brandy",
    "Chocolate Ice-cream": "Unknown",
    "Tequila": "Spirit",
    "Yellow Chartreuse": "Liqueur",
    "Nutmeg": "Spice",
    "Apricot Brandy": "Brandy",
    "Worcestershire Sauce": "Sauce",
    "Southern Comfort": "Liqueur",
    "Orange Juice": "Juice",
    "Sugar": "Mineral",
    "Light Rum": "Rum",
    "Ice": "Water",
    "Kummel": "Liqueur",
    "Drambuie": "Liqueur",
    "Tea": "Tea",
    "Tonic Water": "Soft Drink",
    "Banana": "Fruit",
    "Galliano": "Liqueur",
    "Añejo Rum": "Rum",
    "Egg White": "Unknown",
    "Blended Whiskey": "Whiskey",
    "Campari": "Liqueur",
    "Coffee Brandy": "Brandy",
    "Angostura Bitters": "Bitters",
    "Light Cream": "Cream",
    "Lime": "Fruit",
    "lemon": "Fruit",
    "Creme De Cacao": "Liqueur",
    "Grenadine": "Syrup",
    "Gin": "Gin",
    "Peach brandy": "Brandy",
    "Lemon-lime soda": "Soda",
    "Kahlua": "Liqueur",
    "Benedictine": "Liqueur",
    "White Creme de Menthe": "Liqueur",
    "Orange Bitters": "Bitters",
    "Orange": "Fruit",
    "Club Soda": "Soda",
    "Lime vodka": "Vodka",
    "Blue Curacao": "Liqueur",
    "Wine": "Wine",
    "Amaretto": "Liqueur",
    "Tia Maria": "Liqueur",
    "Pineapple": "Fruit",
    "Lemonade": "Soft Drink",
    "Grapefruit Juice": "Juice",
    "Applejack": "Brandy",
    "Triple Sec": "Liqueur",
    "Lime Juice": "Juice",
    "Dry Vermouth": "Fortified Wine",
    "Water": "Water",
    "Coca-Cola": "Soft Drink",
    "Strawberries": "Fruit",
    "Sweet and Sour": "Unknown",
    "Bourbon": "Whiskey",
    "Green Creme de Menthe": "Liqueur",
    "Egg Yolk": "Unknown",
    "Lemon Peel": "Fruit",
    "Cachaca": "Spirit",
    "Mint": "Herb",
    "Vodka": "Vodka",
    "Irish Whiskey": "Whiskey",
    "Tomato Juice": "Juice",
    "Apple Brandy": "Brandy",
}

alcohol_percentage_dict = {
    "Lemon vodka": 40,
    "Brandy": 40,
    "Apple brandy": 35,
    "Dark rum": 40,
    "Añejo Rum": 38,
    "Amaretto": 28,
    "Apricot Brandy": 24,
    "Whiskey": 40,
    "Spirit": 40,
    "Fortified Wine": 18,
    "Kahlua": 20,
    "Sloe Gin": 26,
    "White Creme de Menthe": 25,
    "Sweet Vermouth": 16,
    "Campari": 24,
    "Coffee Brandy": 30,
    "Blackberry Brandy": 30,
    "Maraschino Liqueur": 32,
    "Kummel": 38,
    "Sherry": 15,
    "Tia Maria": 26.5,
    "Peach Brandy": 30,
    "Irish Whiskey": 40,
    "Soda water": 0,
    "Cherry Brandy": 30,
    "Dry Vermouth": 18,
    "Triple Sec": 40,
    "Southern Comfort": 35,
    "Scotch": 40,
    "Blue Curacao": 20,
    "Galliano": 42.3,
    "Drambuie": 40,
    "Green Chartreuse": 55,
    "Cognac": 40,
    "Green Creme de Menthe": 25,
    "Port": 20,
    "Lime vodka": 40,
    "Dubonnet Rouge": 19,
    "Bourbon": 40,
    "Yellow Chartreuse": 40,
    "Cachaca": 38,
    "Grand Marnier": 40,
    "Light Rum": 40,
    "Coffee Liqueur": 20,
    "Peach brandy": 35,
    "Creme De Cacao": 20,
}
